version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: beymen_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: beymen_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - beymen_network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: beymen_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - beymen_network
    restart: always

  mongo:
    image: mongo:6.0
    container_name: beymen_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - beymen_network
    restart: always

networks:
  beymen_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  mongo_data:
